services:
  authservice:
    build:
      context: ./AuthService
    ports:
      - 1000:3000
    depends_on:
      - mongo-express
      - rabbitmq
  competitionservice:
    build:
      context: ./CompetitionService
    ports:
      - 2000:3000
    depends_on:
      - mongo-express
      - rabbitmq
  fotoanalyseservice:
    build:
      context: ./FotoAnalyseService
    ports:
      - 3000:3000
    depends_on:
      - mongo-express
      - rabbitmq
  gateway:
    build:
      context: ./gateway
    ports:
      - 4000:3000
  submissionimageservice:
    build:
      context: ./SubmissionImageService
    ports:
      - 5000:3000
    depends_on:
        - mongo-express
        - rabbitmq
  targetimageservice:
    build:
      context: ./TargetImageService
    ports:
      - 6000:3000
    depends_on:
      - mongo-express
      - rabbitmq
  mongo-express:
    image: mongo
    restart: always
    ports:
      - 6942:27017
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
