services:
  authservice:
    build:
      context: ./AuthService
    ports:
      - 1000:3000
    depends_on:
      - mongo-express
  competitionservice:
    build:
      context: ./CompetitionService
    ports:
      - 2000:3000
    depends_on:
      - mongo-express
  fotoanalyseservice:
    build:
      context: ./FotoAnalyseService
    ports:
      - 3000:3000
    depends_on:
      - mongo-express
  gateway:
    build:
      context: ./gateway
    ports:
      - 4000:3000
    depends_on:
      - mongo-express
  submissionimageservice:
    build:
      context: ./SubmissionImageService
    ports:
      - 5000:3000
    depends_on:
        - mongo-express
  targetimageservice:
    build:
      context: ./TargetImageService
    ports:
      - 6000:3000
    depends_on:
      - mongo-express
  mongo-express:
    image: mongo
    restart: always
    ports:
      - 6942:27017
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
