global:
  scrape_interval: 10s
  evaluation_interval: 10s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: "targetimageservice"
    static_configs:
      - targets: ["api:6000"]
