# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: 'coverage'

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2

      - name: Linter
        run: npm run lint
